### ISSUE TITLE
primers designed by White et al. (1990)

### ISSUE THREAD

**Issue by frederic-mahe** [pr2database/pr2-primers#3]
Some of the 18S and ITS primers listed in that book chapter from 1990 are still in use today. We should add the 18S primers to our database.
```
NS1 (forward): GTAGTCATATGCTTGTCTC
NS2 (reverse): GGCTGCTGGCACCAGACTTGC
NS3 (forward): GCAAGTCTGGTGCCAGCAGCC
NS4 (reverse): CTTCCGTCAATTCCTTTAAG
NS5 (forward): AACTTAAAGGAATTGACGGAAG
NS6 (reverse): GCATCACAGACCTGTTATTGCCTC
NS7 (forward): GAGGCAATAACAGGTCTGTGATGC
NS8 (reverse): TCCGCAGGTTCACCTACGGA
```
There is no doi, but a scan of the chapter is [available](https://nature.berkeley.edu/brunslab/papers/white1990.pdf).

Also, it might be interesting to include ITS1 (TCCGTAGGTGAACCTGCGG) as it is anchored in the 18S. It is so widely used for fungi studies that, at the very least, it would increase the visibility of this repository.

**Comment by vaulot** [comment]
Thanks a lot Fred, I have added them the MySQL database and will refresh the web page latter.  I also added the ITS ones (I am collecting ITS and 28S primers as well, can be useful latter)....
