### ISSUE TITLE
original references for primers 329F/329R and 528F

### ISSUE THREAD

**Issue by frederic-mahe** [pr2database/pr2-primers#4]
Quick note. The publication [Guillou et al. 2004](https://doi.org/10.1078/143446104774199592) gives older references than the one we currently have for primers 329F/329R and 528F:
 
> The entire SSU rDNA gene was amplified using the eukaryotic primers Euk 328f (5′-ACC TGG TTG ATC CTG CCA G-3′) and Euk 329r (5′-TGA TCC TTC YGC AGG TTC AC-3′) as described in
Moon-van der Staay et al. (2001).

> Partial sequences of PCR products or of clones representative of each RFLP pattern obtained were determined by Qiagen Genomics Sequencing Services, using the internal primer Euk 528f (5′-GCG GTA ATT CCA GCT CCA A-3′; Elwood et al. 1985); (3).

I need to check that.

**Comment by vaulot** [comment]
But if I remember in the Moon paper, she was using primers coming from an obscure Korean paper (but she did not cite it..) - She was a post doc with me...

**Comment by frederic-mahe** [comment]
ok, it seems to be a dead-end. I could not find an older reference.
