### ISSUE TITLE
More fungi-specific 18S primers

### ISSUE THREAD

**Issue by frederic-mahe** [pr2database/pr2-primers#6]
I've seen these primers used in several studies, so you might want to consider including them in the 18S primer database. The original publication seems to be:

Vainio EJ, Hantula J (2000) Direct analysis of wood-inhabiting fungi using denaturing gradient gel electrophoresis of amplified ribosomal DNA. Mycol Res 104: 927–936. https://doi.org/10.1017/S0953756200002471

From table 2 in Vainio & Hantula (2000):

FF390: CGATAACGAACGAGACCT
FF700: GATACCGTNGTAGTCT
FF1100: CCAGCTCCAATAGCGTATATTA

FR1: ANCCATTCAATCGGTANT (reverse)

Note that, in the original publication, primer sequences contain inosine (I) symbols. I've replaced them with Ns.

**Comment by vaulot** [comment]
Thanks a lot Fred, I have added them to the database.  Which combination has been used for metabarcoding in recent studies (with the citation if you have).

**Comment by frederic-mahe** [comment]
Sure, the original paper tested the primer pairs FF390-FR1, FF700-FR1, and FF1100-FR1.

That [2019 preprint](https://www.biorxiv.org/content/10.1101/777383v1.full.pdf) used:

> FF390 and FR1 for V7-V8 region of 18S rRNA amplicons.

They cite a [2015 paper](https://sfamjournals.onlinelibrary.wiley.com/doi/full/10.1111/1751-7915.12162):

>Similarly, an 18S rRNA gene fragment of about 350 bases was amplified using the primers FR1 (5′‐ANCCATTCAATCGGTANT‐3′) and FF390 (5′‐CGATAACGAACGAGACCT‐3′)

Which cites a [2011 paper](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0024166):

> The primer set FR1 (5′-AICCATTCAATCGGTAIT-3′) / FF390 (5′-CGATAACGAACGAGACCT-3′) was developed by Vainio and Hantula.

**Comment by vaulot** [comment]
Merci Fred, added to the database....
